#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$root/../.." && pwd)"
app_dir="$HOME/Applications/Firehawk Focus.app"
contents="$app_dir/Contents"

command -v swift >/dev/null || {
  echo "Swift compiler not found. Install Xcode Command Line Tools: xcode-select --install" >&2
  exit 1
}

echo "==> Building Firehawk Focus (Release)..."
swift build --package-path "$root" -c release

bin_dir="$(swift build --package-path "$root" -c release --show-bin-path)"

echo "==> Creating macOS App Bundle..."
# Kill any currently running instance first
pkill -x "FirehawkFocus" 2>/dev/null || true

rm -rf "$app_dir"
mkdir -p "$contents/MacOS" "$contents/Resources" "$HOME/Applications"

cp "$bin_dir/FirehawkFocus" "$contents/MacOS/FirehawkFocus"
cp "$root/Info.plist" "$contents/Info.plist"
cp "$repo_root/FocusModel.js" "$contents/Resources/FocusModel.js"

# Copy AppIcon
if [ -f "$root/Resources/AppIcon.icns" ]; then
  cp "$root/Resources/AppIcon.icns" "$contents/Resources/AppIcon.icns"
fi

# Copy custom sound resources
if [ -d "$root/Resources/Sounds" ]; then
  cp -R "$root/Resources/Sounds/"* "$contents/Resources/" 2>/dev/null || true
fi

# Copy resource bundle if generated by SwiftPM
if [ -d "$bin_dir/FirehawkFocus_FirehawkFocus.bundle" ]; then
  cp -R "$bin_dir/FirehawkFocus_FirehawkFocus.bundle" "$contents/Resources/"
fi

chmod +x "$contents/MacOS/FirehawkFocus"
codesign --force --deep --sign - "$app_dir"

# Symlink into system /Applications if writable (for instant Spotlight/Launchpad indexing)
ln -sfn "$app_dir" "/Applications/Firehawk Focus.app" 2>/dev/null || true

# Touch the app bundle to force macOS LaunchServices and Finder icon cache refresh
touch "$app_dir"

# Install CLI launcher in ~/.local/bin/firehawk-focus
mkdir -p "$HOME/.local/bin"
cat << 'EOF' > "$HOME/.local/bin/firehawk-focus"
#!/usr/bin/env bash
open -a "$HOME/Applications/Firehawk Focus.app" "$@"
osascript -e 'tell application "Firehawk Focus" to activate' 2>/dev/null || true
EOF
chmod +x "$HOME/.local/bin/firehawk-focus"

# Configure automatic startup at login via LaunchAgent
launch_agents_dir="$HOME/Library/LaunchAgents"
plist_path="$launch_agents_dir/org.lordfirehawk.firehawk-focus.plist"
mkdir -p "$launch_agents_dir"

cat << EOF > "$plist_path"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>org.lordfirehawk.firehawk-focus</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/open</string>
        <string>-a</string>
        <string>$app_dir</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>ProcessType</key>
    <string>Interactive</string>
</dict>
</plist>
EOF

echo "==> Installed Firehawk Focus to: $app_dir"
echo "==> CLI shortcut installed: ~/.local/bin/firehawk-focus"
echo "==> Startup at Login enabled: $plist_path"
echo "==> Launching Firehawk Focus..."
open "$app_dir"

echo "Firehawk Focus is now active in your macOS Menu Bar!"
